#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfd91;
constexpr uint24_t FX_DATA_BYTES = 155342;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

constexpr uint24_t dpad = 0x000000;
constexpr uint24_t abutton = 0x000182;
constexpr uint24_t bbutton = 0x0001E4;
constexpr uint24_t hydraicon = 0x000246;
constexpr uint24_t eggy = 0x0002A8;
constexpr uint24_t hatchingegg = 0x001CEA;
constexpr uint24_t eggcon = 0x00372C;
constexpr uint24_t badegg = 0x00378E;
constexpr uint24_t goopsphere = 0x004C90;
constexpr uint24_t magmalionsphere = 0x005B92;
constexpr uint24_t unagisphere = 0x007994;
constexpr uint24_t bunsphere = 0x008116;
constexpr uint24_t spikersphere = 0x008898;
constexpr uint24_t chimpsphere = 0x00901A;
constexpr uint24_t puppysphere = 0x00979C;
constexpr uint24_t hensphere = 0x009F1E;
constexpr uint24_t crabsphere = 0x00A790;
constexpr uint24_t frogsphere = 0x00AF12;
constexpr uint24_t goatsphere = 0x00B694;
constexpr uint24_t fishsphere = 0x00D496;
constexpr uint24_t horsesphere = 0x00DC18;
constexpr uint24_t frexsphere = 0x00E39A;
constexpr uint24_t harpysphere = 0x00EB1C;
constexpr uint24_t bullsphere = 0x00F29E;
constexpr uint24_t hornetsphere = 0x00FA20;
constexpr uint24_t hypnosphere = 0x0101A2;
constexpr uint24_t lizardsphere = 0x010924;
constexpr uint24_t octosphere = 0x0110A6;
constexpr uint24_t shellysphere = 0x011828;
constexpr uint24_t snakesphere = 0x011FAA;
constexpr uint24_t tortoisesphere = 0x01272C;
constexpr uint24_t bun = 0x01452E;
constexpr uint24_t goop = 0x0146B0;
constexpr uint24_t unagi = 0x014832;
constexpr uint24_t spiker = 0x0149B4;
constexpr uint24_t octo = 0x014B36;
constexpr uint24_t msnake = 0x014CB8;
constexpr uint24_t chicky = 0x014E3A;
constexpr uint24_t hypnot = 0x014FA4;
constexpr uint24_t hornet = 0x01511A;
constexpr uint24_t bull = 0x01529C;
constexpr uint24_t harpy = 0x015406;
constexpr uint24_t frex = 0x015588;
constexpr uint24_t horsey = 0x0156FE;
constexpr uint24_t fishy = 0x015880;
constexpr uint24_t froggy = 0x015A02;
constexpr uint24_t shelly = 0x015B84;
constexpr uint24_t crab = 0x015D06;
constexpr uint24_t puppy = 0x015E88;
constexpr uint24_t lizard = 0x015FDA;
constexpr uint24_t chimp = 0x01615C;
constexpr uint24_t magmalion = 0x0162DE;
constexpr uint24_t goat = 0x01DAE0;
constexpr uint24_t tortoise = 0x01E0E2;
constexpr uint24_t goatwiggle = 0x01E6CC;
